"""Added account table

Revision ID: 11b2d9fd9958
Revises: 35dce248987c
Create Date: 2023-02-19 01:16:19.899955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b2d9fd9958'
down_revision = '35dce248987c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
