"""Added account table

Revision ID: 154e3a520aea
Revises: 11b2d9fd9958
Create Date: 2023-02-19 01:44:18.238520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154e3a520aea'
down_revision = '11b2d9fd9958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
