"""Added account table

Revision ID: 35dce248987c
Revises: 7ff2dfeba470
Create Date: 2023-02-18 23:58:14.837565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dce248987c'
down_revision = '7ff2dfeba470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
