"""Added account table

Revision ID: 7ff2dfeba470
Revises: e56ec499fc55
Create Date: 2023-02-18 23:56:15.173805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff2dfeba470'
down_revision = 'e56ec499fc55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
