"""first table creation

Revision ID: 866d201bbc7b
Revises: 5503d499cecb
Create Date: 2023-02-07 11:04:42.224098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866d201bbc7b'
down_revision = '5503d499cecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'location')
    op.drop_column('roles', 'contact')
    op.drop_column('roles', 'device')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('device', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
