"""Addedtable

Revision ID: a213f24be95a
Revises: 866d201bbc7b
Create Date: 2023-02-07 18:11:13.224627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a213f24be95a'
down_revision = '866d201bbc7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'isActive')
    # ### end Alembic commands ###
