"""Added account table

Revision ID: a2d584f252e2
Revises: 24fc7be6a4f7
Create Date: 2023-02-15 10:14:56.165299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d584f252e2'
down_revision = '24fc7be6a4f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'contact')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
