"""Added account table

Revision ID: a834f0d0b36c
Revises: a2d584f252e2
Create Date: 2023-02-15 10:35:01.618538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a834f0d0b36c'
down_revision = 'a2d584f252e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
