"""Added account table

Revision ID: dd54c86422b4
Revises: af0affb610e1
Create Date: 2023-02-19 02:24:18.898355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd54c86422b4'
down_revision = 'af0affb610e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
