"""Added account table

Revision ID: e56ec499fc55
Revises: a834f0d0b36c
Create Date: 2023-02-15 10:54:33.451793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56ec499fc55'
down_revision = 'a834f0d0b36c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
